language: node_js

sudo: false

node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_module

script:
  - npm run build
  - npm run clean
  - npm test

after_success: npm run coverage

